### ISSUE TITLE
Search engine optimization

### ISSUE THREAD

**Issue by SushilShrestha** [foss-np/sabda#23]
I had heard about this repository and was trying to find this repository. First thing I tried was to search through github search and then with search engines. But couldn't find any link to this repo through search. So just suggesting if we can add keywords to the readme file or project descriptions for the search engine optimization. 

Following are the keywords, I used
nepali lyrics repo
nepali lyrics github

Also is this a Nepali songs only repository or can include any song?

**Comment by rhoit** [comment]
tags has been added
