### ISSUE TITLE
Github pages for the repo

### ISSUE THREAD

**Issue by SushilShrestha** [foss-np/sabda#27]
Is it possible for us to maintain a github page for this repo? Just a navigable webpage for now

**Comment by rhoit** [comment]
ya i guess so!

**Comment by SushilShrestha** [comment]
Hi @rhoit, I have requested pull request for the feature. demo is available in sushilshrestha.github.io/sabda

**Comment by rhoit** [comment]
@SushilShrestha may be we can the add the code to new branch in repo itself!

**Comment by SushilShrestha** [comment]
yup we can do that. so our normal workflow would be.

After we receive new lyrics:
1. merge the `master` with `src` branch
2. generate templates on `src` branch
3. switch to `gh-pages` and commit the updates
4. push the `gh-pages` branch

**Comment by rhoit** [comment]
sounds good to me!

**Comment by SushilShrestha** [comment]
Also can we remove all the lyrics from the `gh-page` and only have the templates on `gh-page`? and make sure `gh-page` is never merged to `master`.

**Comment by rhoit** [comment]
@SushilShrestha if `gh-page` is orphan branch it won't be merge we need not worry about that, so goes for `src` branch.

**Comment by SushilShrestha** [comment]
Didn't know such feature exists(`--orphan`). Thanks @rhoit. learned a new thing today 🎉

I have updated the changes to a [new fork](https://github.com/SushilShrestha/sabda)

- [x] `src` and `gh-pages` branches are orphan branches
- [x] Readme for src branch includes the process I followed to generate the files

@rhoit can you review [the new fork](https://github.com/SushilShrestha/sabda). I will send the pull request afterwards.

Thanks again @rhoit 🎉🎉🎉

**Comment by rhoit** [comment]
@SushilShrestha everything seems good to me in https://github.com/SushilShrestha/sabda.

**Comment by SushilShrestha** [comment]
Okay @rhoit, will push the changes to the repo.

**Comment by SushilShrestha** [comment]
Done pushing all the changes.
