### ISSUE TITLE
Requested Song: malai america yehi

### ISSUE THREAD

**Issue by thegauraw** [foss-np/sabda#3]
https://www.youtube.com/watch?v=hErPFTzCK4U

आह  होई   ...
( काम   पाइएन  डिग्री पास  गरेर ,
भैँसी पाले  गाउँ  तिरै  झरेर ...

चिन्ता  छैन  केहि ...
मलाई  अमेरिका  येइ , मलाई  जापान  पनि  येइ , मलाई  बेलायत  नि  येइ ...

लैनो  भैँसी  दुहुन्छु ,
दुइ  गिलास  दुध  खान्छु , 

मलाई  बियर  पनि  येइ , मलाई  व्हिस्की पनि  येइ, मलाई  पोसिलो  नि  येइ 
एह  मलाई  पोसिलो  नि  येइ  हो, पोसिलो  नि  येइ,  मलाई  पोसिलो  नि  येइ  ) x २

आह  होई   ...
( बुढा  पनि  छन्  कुरा  बुझ्दिने , 
ठुला  भैँसी  पाल्या  छन्  दुध  दिने ..

चिन्ता  छैन  केहि ...
मलाई  बहराइन  पनि  येइ, मलाई  इजराइल  पनि  येइ , मलाई  कुवेत  पनि  येइ ...

घिउ  बेच्न लाइ   जान्छु, 
ठेकीको  मोही  खान्छु, 
मलाई  फ्यान्टा  पनि  येइ, मलाई  कोक  भने  नि  येइ, मलाई  पोसिलो  नि  येइ 

एह  मलाई  पोसिलो  नि  येइ  हो ,पोसिलो  नि  येइ ,  मलाई  पोसिलो  नि  येइ  ) x २

आह  होई   ...
(बाख्रा  पाल्छु , राम्रो  छ  बजार 
दुईटा  बोका  बेच्यो  कि  बिस  हजार 

चिन्ता  छैन  केहि ...
मलाई  कोरिया  नि येइ , मलाई  हङकङ  पनि  येइ , मलाई  अस्ट्रेलिया  येइ 

कोदो  पिस्न  जान्छु , 
ड्याम्मै  ढिडो  खान्छु 
मलाई  मोमो  पनि  येइ , मलाई  पिज्जा  पनि  येइ , मलाई  मिठो  पनि  येइ 

मलाई  मिठो  पनि  येइ  हो , मिठो  पनि  येइ , मलाई  मिठो  पनि  येइ .. ) x २

आह  होई   ...
( ताजा  ताजा  बेच्याछ,  खाइयाछ, 
काउली, भन्टा , गोलभेडा  लाइयाछ 

चिन्ता  छैन  केहि ...
मलाई  सिंगापुर  नि  येइ , मलाई  बेल्जियम  नि  येइ , मलाई  क्यानाडा नि  येइ 

एह  प्यारो  छ  येइ  माटो , 
खान्छु  गुन्द्रुक , आटो 

मलाई  चिकेन  पनि  येइ , मलाई  मटन   पनि  येइ , मलाई  मिठो  पनि  येइ 
मलाई  मिठो  पनि  येइ  हो , मिठो  पनि  येइ , मलाई  मिठो  पनि  येइ .. ) x २

आह  होई   ...
(विदेश  गइ , धेरै  बेर  बसिन ,
किन  बेच्ने  रगत  र  पसिना 

चिन्ता  छैन  केहि ...
मलाई  कतार  पनि  येइ , मलाई  दुवै  पनि  येइ , मलाई  मलेसिया  येइ 

एह  पायल  चप्पल  किन्छु , 
कछाड  बेर्छु  , हिड्छु 

एह  मलाई  डिङ्गो  जुत्ता  येइ , मलाई  जिनको  पायन्ट येइ , मलाई  सुहाउने  पनि  येइ 
मलाई  सुहाउने  पनि  येइ  हो , सुहाउने  पनि  येइ , मलाई  सुहाउने  पनि  येइ ... ) x२ 

आह  होई   ...
( कोइ हिँडाइए , कोइ  आफै  हिँडिए ...
कति  चेली  बेचिए , किनिए 

चिन्ता  छैन  केहि ...
मलाई  भारत  पनि  येइ , मलाई  थाइल्याण्ड  पनि  येइ , मलाई  जर्मन  पनि  येइ 

खान्छ्म  गेडा  गुडी , 
बस्छ्म  बुडा , बुडी 

मलाई  सलमान  खान  नि  येइ , मलाई  शाहरुख  खान  नि  येइ , मलाई  ह्यान्सम  पनि  येइ ..
मलाई  ह्यान्सम  पनि  येइ  हो , ह्यान्सम  पनि  येइ , मलाई  ह्यान्सम  पनि  येइ  ) x२

**Comment by rhoit** [comment]
send the pull request see issue #7 for the reason.
