### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by samundra** [foss-np/sabda#6]
### Documentation on Contribution

I have very little knowledge of LRC format. I can surely do some research and then gather enough information to start with but it would take fair amount of time. A quick introduction along with sample contribution would surely help from the guys who have already been doing it. How about having a quick introdution documentation on **How to contribute?**

Even if its simple text editing a general guideline would help in this case.

```
[ar: The Underdogs] - Artist Name
[ti: के रे?] - song tile
[length: 05:05] - total length of songs
[by: rho] - contributor

[00:15.00] माया तिमीलाई नलाए के भो
[00:17.00] तिमी अझै मेरो साथी नै हो
[00:20.00]
... ... ... ... ... ... ... ...
... ... ... ... ... ... ... ...
[04:40.30] तिमी अझै मेरो साथी नै हो
[04:44.00]

[04:46.00] synced by =haude=
```
### How to import LRC Format ?
- This varies from player to player. So, it can be asked to refer to their player documentation on "how to do it on their player".
### List of Players these LRC were tested with
- A list of players where these LRC files were tested would really help. I am thinking of using these but I am confused where to start with?
### Tools used to create LRC files

General introduction on the tools used to create sync these lyrics.

**Comment by rhoit** [comment]
### how to contribute

About contribution there isn't any hard and fast rule, I guess its pretty self explanatory, about the folder structure and stuff. I'm unable to think what should be written.. why don't you help me out here.

There is nothing much about lrc to be said.. [wikipedia](https://en.wikipedia.org/wiki/LRC_%28file_format%29) is more are less everything. 

### How to import LRC Format ?

In Arch, AUR uses  [PedroHLC](https://github.com/PedroHLC/osdlyrics) fork of [osdlyrics](https://github.com/osdlyrics/osdlyrics), i use the same thing. which supports major audio of players.

### List of Players these LRC were tested with

I use [banshee](http://banshee.fm/download/), with osdlyrics.

### Tools used to create LRC files

LRC is plain text format, use anything.. I use leafpad.

**Comment by samundra** [comment]
> why don't you help me out here

Sure, I would love to. Let me go through the details first. I will try to load the currently available lyrics. Once I feel comfortable enough we can get started on it. :smile: 

**Regarding Tools** I was thinking some sort of tool where songs can be played and side by side we can  write the lyrics. It's kind of tough to sync up the audio with lyrics.

**Comment by rhoit** [comment]
anything you want to add into README @samundra its quite updated from before.

**Comment by samundra** [comment]
@rhoit It looks much better now.
