### ISSUE TITLE
I propose this as Database Structure 

### ISSUE THREAD

**Issue by RupGautam** [foss-np/sabda#8]
How about this structure? For the sake of browsing and find experience. 

![music_catelog](https://cloud.githubusercontent.com/assets/4873392/14130902/7c51c5a8-f604-11e5-81d2-b721da5fb5fa.png)

We can do more complex struture than this sample but I don't think we will have enough metadata to have somthing like this: 
![](https://www.e-education.psu.edu/spatialdb/sites/www.e-education.psu.edu.spatialdbd7/files/music_erd-jls.gif)

**Comment by rhoit** [comment]
@RupGautam Its great idea but, we barely have adequate amount of collection to get lost into.
I would prefer to wait for a while, until collection grows. And I'm not sure how the lrc softwares will handle auto-fetch, but that's the different story.

For now simple `<Artist>/<Album>/<Title>.lrc` will do the trick.

**Comment by jitendraharlalka** [comment]
Just a suggestion: For several albums/tracks, many of the fields are unavailable or not applicable. NoSQL datastore would be more appropriate I feel.

**Comment by scimad** [comment]
> @RupGautam Its great idea but, we barely have adequate amount of collection to get lost into.
> I would prefer to wait for a while, until collection grows. And I'm not sure how the lrc softwares will handle auto-fetch, but that's the different story.
> 
> For now simple `<Artist>/<Album>/<Title>.lrc` will do the trick.

Marking the issue closed endorsing @rhoit.
